config/routes.rb
Socialink::Application.routes.draw do
  devise_for :users

  resources :users

  get "users/index"

  resources :links
  match "/:encoded" => "links#redir"
  root :to=>"links#new", :as => 'links_path'

end

app/models/hit.rb
class Hit < ActiveRecord::Base
  belongs_to :adress
end

app/models/link.rb
class Link < ActiveRecord::Base
  has_many :hits

  validates_presence_of :url
  validate :normalize_url

  def normalize_url
    begin
      nuri=URI.parse self.url
      nuri.normalize
      if ( nuri.to_s =~ /^(http|https):\/\// )
        self.url=nuri
      else
        self.url="http://"+nuri.to_s
      end
    rescue
      errors.add(:url, "seems to be wrong")
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  # GET /links
  # GET /links.xml
  def index
    @links = Link.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @links }
    end
  end

  # GET /links/1
  # GET /links/1.xml
  def show
    @link = Link.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @link }
    end
  end

  # GET /encoded
  def redir
    @link = Link.find(UrlCoder.decode_base(params["encoded"]))
    @hit=@link.hits.create
    @hit.save
    redirect_to @link.url
  end

  # GET /links/new
  # GET /links/new.xml
  def new
    @link = Link.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @link }
    end
  end

  # GET /links/1/edit
  def edit
    @link = Link.find(params[:id])
  end

  # POST /links
  # POST /links.xml
  def create
    @link = Link.new(params[:link])
    respond_to do |format|
      if @link.save
        format.json { render :json => 
          JsonFormater.format(flash, @link, {
            :shorturl => APP_CONFIG["domain_url"]+"/"+UrlCoder.encode_base(@link.id),
            :longurl => @link.url
          })
        }
        format.html { render :action => "show" }
      else
        format.html { render :action => "new" }
        format.json { render :json => JsonFormater.format(flash, @link)}
      end
    end
  end

  # PUT /links/1
  # PUT /links/1.xml
  def update
    @link = Link.find(params[:id])

    respond_to do |format|
      if @link.update_attributes(params[:link])
        format.html { redirect_to(@link, :notice => 'Link was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @link.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  # DELETE /links/1.xml
  def destroy
    @link = Link.find(params[:id])
    @link.destroy

    respond_to do |format|
      format.html { redirect_to(links_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
  def encoded_url
  	  APP_CONFIG["domain_url"]+"/"+UrlCoder.encode_base(@link.id) 
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Socialink</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= javascript_include_tag 'formatedJson' %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/links/_form.html.erb
<%= form_for(@link, :remote => true, :html => {'data-type' => 'json'} ) do |f| %>
  <% if @link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% @link.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url %>
    <%= f.url_field :url %>
  </div>
  <div class="actions">
    <%= f.submit :value=>'Acortar'%>
  </div>
<% end %>

app/views/links/edit.html.erb
<h1>Editing link</h1>

<%= render 'form' %>

<%= link_to 'Show', @link %> |
<%= link_to 'Back', links_path %>

app/views/links/index.html.erb
<h1>Listing links</h1>

<table>
  <tr>
    <th>Url</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @links.each do |link| %>
  <tr>
    <td><%= link.url %></td>
    <td><%= link_to 'Show', link %></td>
    <td><%= link_to 'Edit', edit_link_path(adress) %></td>
    <td><%= link_to 'Destroy', link, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Link', new_link_path %>

app/views/links/new.html.erb
<div>
<ul id="session">
  <li>login</li>
  <li>register</li>
</ul>
</div>
<div id="linkbox">
  <h1>Link<span class="highlight">r</span></h1>
  <ul id="errors"></ul>
<%= render 'form' %>
  <dl id="urls"></dl>
</div>

app/views/links/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Url:</b>
  <%= link_to encoded_url,encoded_url%>
</p>